name: release

on:
  workflow_dispatch: # manual trigger
  schedule:
    - cron: "0 0 * * *" # Everyday at ~00:00 UTC

jobs:
  build:
    name: build / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    env:
      CARGO_INCREMENTAL: 0
      RUST_BACKTRACE: full

    outputs:
      tag: ${{ steps.now.outputs.formattedTime }}

    steps:
      - name: Get current date # To use as tag
        uses: 1466587594/get-current-time@v1
        id: now
        with:
          format: YYYY.MM.DD

      - name: Enable long paths on windows
        if: startsWith(matrix.os, 'windows')
        run: git config --global core.longpaths true

      - name: Clone repository
        uses: actions/checkout@v2
        with:
          repository: "denoland/deno"
          fetch-depth: 1 # No need for full version history
          submodules: true

      - name: Get commit hash # For release notes
        id: commit
        run: echo "::set-output name=hash::$(git rev-parse HEAD)"

      - name: Setup Deno
        if: startsWith(matrix.os, 'ubuntu')
        uses: denolib/setup-deno@v2.1.0
        with:
          deno-version: v1.2.2

      - name: Generate Release Notes
        if: startsWith(matrix.os, 'ubuntu')
        run: |
          deno run -A https://denonightly.now.sh/notes -h ${{ steps.commit.outputs.hash }} -t ${{ secrets.GITHUB_TOKEN }} -b ${{ steps.now.outputs.formattedTime }}
          deno run -A https://denonightly.now.sh/notes -h ${{ steps.commit.outputs.hash }} -t ${{ secrets.GITHUB_TOKEN }} -b latest

      - name: Upload release notes
        uses: actions/upload-artifact@v2
        if: startsWith(matrix.os, 'ubuntu')
        with:
          name: notes
          path: |
            ${{ steps.now.outputs.formattedTime }}.md
            latest.md
          if-no-files-found: error

      - name: Setup Rust
        uses: hecrj/setup-rust-action@v1
        with:
          rust-version: 1.46.0

      - name: Build
        run: cargo build --release --locked --all-targets

      - name: Zip linux release
        if: startsWith(matrix.os, 'ubuntu')
        working-directory: target/release
        run: zip -r deno-nightly-x86_64-unknown-linux-gnu.zip deno

      - name: Zip mac release
        if: startsWith(matrix.os, 'macOS')
        working-directory: target/release
        run: zip -r deno-nightly-x86_64-apple-darwin.zip deno

      - name: Zip windows release
        if: startsWith(matrix.os, 'windows')
        working-directory: target/release
        run: Compress-Archive -CompressionLevel Optimal -Force -Path deno.exe -DestinationPath deno-nightly-x86_64-pc-windows-msvc.zip

      - name: Export Stable Type Docs
        if: startsWith(matrix.os, 'ubuntu')
        working-directory: target/release
        run: ./deno types > lib.deno-nightly.d.ts

      - name: Export Unstable Type Docs
        if: startsWith(matrix.os, 'ubuntu')
        working-directory: target/release
        run: ./deno types --unstable > lib.deno-nightly.unstable.d.ts

      - name: Upload Builds
        uses: actions/upload-artifact@v2
        with:
          name: release
          path: |
            target/release/deno-nightly-x86_64-unknown-linux-gnu.zip
            target/release/deno-nightly-x86_64-apple-darwin.zip
            target/release/deno-nightly-x86_64-pc-windows-msvc.zip
            target/release/lib.deno-nightly.d.ts
            target/release/lib.deno-nightly.unstable.d.ts

  upload:
    name: upload / ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["latest", "${{ needs.build.outputs.tag }}"]

    needs: build
    steps:
      - name: Download Builds
        uses: actions/download-artifact@v2

      - name: ${{ matrix.tag }}
        uses: ncipollo/release-action@v1
        with:
          tag: "${{ matrix.tag }}"
          name: "${{ matrix.tag }}"
          prerelease: ${{ matrix.tag == "latest" }}
          allowUpdates: true
          replacesArtifacts: true
          artifacts: "release/*"
          bodyFile: "notes/${{ matrix.tag }}.md"
          token: ${{ secrets.GITHUB_TOKEN }}
